function Wmatrix = W_tau_fun(in1,in2,in3)
%W_TAU_FUN
%    WMATRIX = W_TAU_FUN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Jul-2024 15:16:55

ddq1 = in3(1,:);
ddq2 = in3(2,:);
ddq3 = in3(3,:);
dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t6 = q1+q2;
t7 = q2+q3;
t8 = dq1.^2;
t9 = dq2.^2;
t10 = dq3.^2;
t11 = cos(t7);
t12 = q3+t6;
t13 = sin(t6);
t14 = sin(t7);
t17 = ddq1.*t3.*(2.5e+1./1.4e+1);
t18 = ddq2.*t3.*(2.5e+1./1.4e+1);
t19 = ddq3.*t3.*(2.5e+1./2.8e+1);
t20 = dq1.*dq3.*t5.*(2.5e+1./1.4e+1);
t21 = dq2.*dq3.*t5.*(2.5e+1./1.4e+1);
t22 = t5.*t10.*(2.5e+1./2.8e+1);
t15 = sin(t12);
t16 = (ddq1.*t11)./2.0;
t23 = -t20;
t24 = -t21;
t25 = (t8.*t14)./2.0;
t26 = -t22;
t27 = t13.*(9.81e+2./7.0e+1);
t28 = t15.*(9.81e+2./7.0e+1);
Wmatrix = reshape([ddq1,0.0,0.0,ddq2,ddq1+ddq2,0.0,ddq3,ddq3,ddq1+ddq2+ddq3,t17+t18+t19+t23+t24+t26+t28+ddq1.*t11+(ddq2.*t11)./2.0+(ddq3.*t11)./2.0-(t9.*t14)./2.0-(t10.*t14)./2.0-dq1.*dq2.*t14-dq1.*dq3.*t14-dq2.*dq3.*t14,t16+t17+t18+t19+t23+t24+t25+t26+t28,t16+t25+t28+ddq1.*t3.*(2.5e+1./2.8e+1)+ddq2.*t3.*(2.5e+1./2.8e+1)+t5.*t8.*(2.5e+1./2.8e+1)+t5.*t9.*(2.5e+1./2.8e+1)+dq1.*dq2.*t5.*(2.5e+1./1.4e+1),t27+ddq1.*t2+(ddq2.*t2)./2.0-(t4.*t9)./2.0-dq1.*dq2.*t4,t27+(ddq1.*t2)./2.0+(t4.*t8)./2.0,0.0,981*sin(q1)/70,0.0,0.0],[3,6]);
