function robot=reshape2(robot)

n=robot.DoF;
inx=1:n;
robot.taud.w=[robot.taud.w(2*n+1:3*n,:);...
              robot.taud.w(2*inx-1,:);...
              robot.taud.w(2*inx,:);...
              zeros(n,size(robot.taud.w,2));...
              robot.taud.w(3*n+1:end,:)];
robot.tauc.w=[robot.tauc.w(2*n+1:3*n,:);...
              robot.tauc.w(2*inx-1,:);...
              robot.tauc.w(2*inx,:);...
              robot.tauc.w(3*n+1:end,:);...
              zeros(n,size(robot.tauc.w,2))];
robot.taug.w=[robot.taug.w(2*n+1:3*n,:);...
              robot.taug.w(2*inx-1,:);...
              robot.taug.w(2*inx,:);...
              zeros(n,size(robot.taug.w,2));...
              zeros(n,size(robot.taug.w,2))];


end

